name: copy test

on:
  push:
    branches:
      - 7.7
    paths:
      - '.github/workflows/copy.yml'
  workflow_dispatch:

jobs:
  copy:
    runs-on: tomcat-server
    steps:
      - uses: actions/checkout@v5
      - name: copy file
        shell: bash
        run: |
          # Use the appropriate command for the Windows shell
          # For PowerShell:
          Write-Host "Current location is: $(pwd)"
          Get-ChildItem 
          Copy-Item -Path "pom.xml" -Destination "D:\Documents"
