name: copy test

on:
  push:
    branches:
      - 7.7
    paths:
      - '.github/workflows/copy.yml'
  workflow_dispatch:

jobs:
  copy:
    runs-on: tomcat-server
    steps:
      - uses: actions/checkout@v5
      - name: copy file
        shell: pwsh
        run: |
          Get-Location
          Get-ChildItem
          Copy-Item "pom.xml" -Destination "D:\Documents" -Force
