name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java Setup
        uses: actions/setup-java@v5.0.0
        with: 
          java-version: '8'
          distribution: 'temurin'
          cache: "maven"

      - name: Build
        run: mvn clean package

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          path: target/**.war

  deploy:
    needs: build
    environment:
      name: DEV
      url: ${{ vars.URL }}
    runs-on: tomcat-server
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v5.0.0
        with:
          path: artifact

      - name: Deploy WAR file
        run: |
          Copy-Item -Path "artifact\addressbook-2.0.war" -Destination "C:\Program Files\Apache Software Foundation\Tomcat 10.1_Tomcat-10\webapps" -Force
        shell: powershell
  
      - name: Restart Tomcat service
        run: |
          Write-Host "Stopping Tomcat service..."
          Stop-Service -Name "Tomcat-10" -Force
          Start-Sleep -Seconds 5
          Write-Host "Starting Tomcat service..."
          Start-Service -Name "Tomcat-10"
          Write-Host "Tomcat restarted successfully."
        shell: powershell
